<a href="https://colab.research.google.com/github/SohamBothara/python_ml_projects/blob/main/Numpy_Total.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

List vs Numpy --> Time Taken

In [2]:
from time import process_time

Time taken by the list

In [5]:
python_list=[i for i in range(10000)]

start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.000481899999999591


Time taken by Numpy array

In [6]:
np_array=np.array([i for i in range(10000)])

start_time=process_time()
np_array+=5 #np_array=np_array+5
end_time=process_time()
print(end_time-start_time)

0.00011213099999984877


Numpy Arrays

In [9]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [12]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [13]:
#creating 1 dimensional array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [14]:
a.shape

(4,)

In [15]:
b= np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
b.shape

(2, 4)

In [18]:
c=np.array([(1,2,3.015,4),(5,6,7,8)],dtype=float)
print(c)

[[1.    2.    3.015 4.   ]
 [5.    6.    7.    8.   ]]


Initial Placeholders in numpy arrays

In [20]:
# create a numpy array pf zeroes
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
#create a numpy array of ones
y=np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
#array of particular value
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [24]:
# create an identity matrix
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
#create a numpy array with random values
s=np.random.random((3,4))
print(s)

[[0.80849894 0.85402388 0.76516024 0.28405683]
 [0.66724581 0.48556434 0.45414719 0.88739244]
 [0.95194998 0.35454804 0.04765597 0.19396491]]


In [26]:
#random integer value array within a specific integer
c=np.random.randint(10,100,(3,5))
print(c)

[[65 96 80 51 36]
 [46 94 11 37 15]
 [98 30 39 20 27]]


In [30]:
#array of evenly spaced values  --> specifying the number of vlaues required
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [31]:
#array of evenly spaced values  -->  specifying the step
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [32]:
#convert list to an numpy array
list2=[10,20,30,40,50]

np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [33]:
c=np.random.randint(10,90,(5,5))
print(c)

[[55 80 27 69 30]
 [71 65 24 57 31]
 [81 49 85 10 22]
 [25 36 20 68 20]
 [19 28 72 87 68]]


In [34]:
c.shape

(5, 5)

In [35]:
c.ndim

2

In [36]:
#checking the number of elements in the array
c.size

25

In [37]:
#checking the datatype of the values pf the arrat
c.dtype

dtype('int64')

Mathematical Operations on an numpy array

In [38]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [39]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

In [40]:
print(a)
print(b)

[[2 6 7]
 [0 8 7]
 [3 2 9]]
[[19 19 15]
 [18 14 15]
 [14 15 13]]


In [42]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[21 25 22]
 [18 22 22]
 [17 17 22]]
[[-17 -13  -8]
 [-18  -6  -8]
 [-11 -13  -4]]
[[ 38 114 105]
 [  0 112 105]
 [ 42  30 117]]
[[0.10526316 0.31578947 0.46666667]
 [0.         0.57142857 0.46666667]
 [0.21428571 0.13333333 0.69230769]]


In [44]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[21 25 22]
 [18 22 22]
 [17 17 22]]
[[-17 -13  -8]
 [-18  -6  -8]
 [-11 -13  -4]]
[[ 38 114 105]
 [  0 112 105]
 [ 42  30 117]]
[[0.10526316 0.31578947 0.46666667]
 [0.         0.57142857 0.46666667]
 [0.21428571 0.13333333 0.69230769]]


Array Manipulation


In [45]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 7 8]
 [9 7 6]]
(2, 3)


In [46]:
#transpose
trans=np.transpose(array)
print(trans)
trans.shape

[[3 9]
 [7 7]
 [8 6]]


(3, 2)

In [48]:
trans2=array.T
print(trans2)
trans2.shape

[[3 9]
 [7 7]
 [8 6]]


(3, 2)

In [49]:
#reshaping the array
a=np.random.randint(0,20,(2,3))
print(a)
a.shape

[[ 2 16  9]
 [15 13 13]]


(2, 3)

In [50]:
b=a.reshape(3,2)
print(b)
b.shape

[[ 2 16]
 [ 9 15]
 [13 13]]


(3, 2)